/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proje;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    

    @Test 
    public void testFound(){

        ArrayList<Integer> array =new ArrayList<>(Arrays.asList(1,2,3,4));

        assertTrue(App.hasMean(array,2,8,0));
    }

    @Test 
    public void testNotFound(){

        ArrayList<Integer> array =new ArrayList<>(Arrays.asList(1,2,3,4));

        assertFalse(App.hasMean(array,2,8,8));
    }

    @Test 
    public void testEmptyArray(){

        ArrayList<Integer> array =new ArrayList<>();

        assertFalse(App.hasMean(array,2,8,8));
    }

    @Test 
    public void testNullArray(){

        assertFalse(App.hasMean(null,2,8,8));
        
    }

    @Test 
    public void testNullArgument(){

        ArrayList<Integer> array =new ArrayList<>();

        assertFalse(App.hasMean(array,null,8,8));
    }
}
